export const OBTENER_CATALOGO = 'OBTENER_CATALOGO'
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO' 
export const CONFIRMAR_COMPRA = 'CONFIRMAR_COMPRA'

export const CONFIRMAR_ORDEN = 'CONFIRMAR_ORDEN'
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN'
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL'